methodology: Other
dataset_source: Insecurity Insight
package_creator: HDX Data Systems Team
private: False
maintainer: 878dc76d-d357-4dce-8562-59f6421714e1
owner_org: 648d346e-3995-44cc-a559-29f8192a3010
subnational: "1"
data_update_frequency: "-2"
