license_id: cc-by-igo
methodology: Other
methodology_other: Systematically collected from open source using the SiND.
caveats: ""
dataset_source: Insecurity Insight
package_creator: HDX Data Systems Team
private: False
maintainer: insecurityinsight
owner_org: insecurity-insight
data_update_frequency: -1
notes: ""
