# This workflow will install Python dependencies and run the script

name: Run Insecurity Insight Script

on:
    workflow_dispatch: # add run button in GitHub UI
    schedule: #  Run script according to a cron schedule
    # - cron: "0 7 * * *" # schedule for test
    - cron: "0 7 * * MON" # Schedule for production

jobs:
  build:
    environment: 
        name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        make install
    - name: Run script
      env: #  Environment variables mapped from GitHub repository's secrets to be used by script
        HDX_KEY_STAGE: ${{ secrets.HDX_KEY_STAGE }}
        HDX_KEY: ${{ secrets.HDX_BOT_SCRAPERS_API_TOKEN }}
        HDX_SITE: ${{ vars.HDX_SITE }}
        USER_AGENT: ${{ vars.USER_AGENT }}
        PREPREFIX: ${{ vars.PREPREFIX }}
      run: |
        make run
    - name: Send mail
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{secrets.EMAIL_SERVER}}
        server_port: ${{vars.EMAIL_PORT}}
        username: ${{vars.EMAIL_USERNAME}}
        password: ${{secrets.EMAIL_PASSWORD}}
        subject: "FAILED: ${{github.repository}} run job"
        body: GitHub Actions run job for ${{github.repository}} failed!
        to: ${{secrets.EMAIL_LIST}}
        from: ${{vars.EMAIL_FROM}}

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1